#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Action {
    Tick,
    Quit,
    NextScreen,
    PrevScreen,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    AdjustSelected(i32),
    ActivateSelected,
    RefreshDevices,
    ConnectSelected,
    Disconnect,
    RefreshConfig,
    ShowPacketLog,
    ToggleApplyModal,
    ConfirmApply,
    CancelModal,
    TogglePadSelection,
    ClearPadSelection,
    UndoField,
    DiscardAll,
    ShowHelp,
}
